name: PROD deployment
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Remove useless files
        run: |
          rm -fr .git .github
      - name: Upload to Hoststar
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
          server-dir: ${{ secrets.FTP_UPLOAD_DIR }}
          log-level: verbose