name: PROD deployment
on:
  workflow_dispatch:
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Upload to Hoststar
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps-legacy
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
          server-dir: ${{ secrets.FTP_UPLOAD_DIR }}
          dry-run: true
          log-level: verbose